import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher_string.dart';

import 'media_reference.dart';
import 'media_store_io.dart'
    if (dart.library.html) 'media_store_web.dart';

/// Resolves any image reference the app stores in a message.
///
/// Supported forms: absolute local paths (images generated by a local
/// sd.cpp server), `data:image/...` URIs (web, or imported avatars) and
/// remote `http(s)` URLs (Civitai).
ImageProvider mediaImageProvider(String reference) {
  final ref = reference.trim();
  if (isDataImageReference(ref)) {
    final bytes = decodeDataImageReference(ref);
    if (bytes != null) return MemoryImage(bytes);
  }
  if (isRemoteImageReference(ref)) return NetworkImage(ref);
  final local = localMediaImageProvider(ref);
  if (local != null) return local;
  // Unusable reference: let the widget's error builder show the failure
  // instead of throwing while the tree is built.
  return MemoryImage(Uint8List(0));
}

/// Persists freshly generated image bytes and returns a reference that
/// [mediaImageProvider] can render and the chat history can store.
Future<String> storeGeneratedMediaImage(Uint8List bytes, String extension) =>
    storeGeneratedImage(bytes, extension);

/// Image widget for a chat/media reference, with loading and error states.
class MediaImage extends StatelessWidget {
  final String reference;
  final BoxFit fit;

  const MediaImage(this.reference, {super.key, this.fit = BoxFit.contain});

  @override
  Widget build(BuildContext context) {
    return Image(
      image: mediaImageProvider(reference),
      fit: fit,
      loadingBuilder: (context, child, loadingProgress) {
        if (loadingProgress == null) return child;
        return Center(
          child: CircularProgressIndicator(
            value: loadingProgress.expectedTotalBytes != null
                ? loadingProgress.cumulativeBytesLoaded /
                    loadingProgress.expectedTotalBytes!
                : null,
          ),
        );
      },
      errorBuilder: (context, error, stackTrace) => const Icon(Icons.error),
    );
  }
}

/// Opens the full size image with the platform viewer/browser.
Future<bool> openMediaReference(String reference) async {
  final ref = reference.trim();
  if (ref.isEmpty) return false;
  if (isRemoteImageReference(ref)) return launchUrlString(ref);
  // Inline data URIs cannot be handed to the platform viewer.
  if (isDataImageReference(ref)) return false;
  final uri = openableLocalMediaUri(ref);
  if (uri == null) return false;
  return launchUrlString(uri.toString());
}
